version: '3.1'

services:

  db:
    image: mysql
    container_name: atom_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_DATABASE=atom
      - MYSQL_USER=atom
      - MYSQL_PASSWORD=atom
      - MYSQL_ROOT_PASSWORD=atom
    ports:
      - "3307:3306"

  adminer:
    container_name: atom_adminer
    image: adminer
    restart: always
    ports:
      - 9000:8080